// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SampleWSApp.Client.Shipment {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="ShipmentSoap", Namespace="http://www.cesun.edu")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Shipment : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SecurityHeader SecurityHeaderValueField;
        
        private System.Threading.SendOrPostCallback SendOperationCompleted;
        
        public Shipment() {
            this.Url = "http://localhost:8080/Shipment.asmx";
        }
        
        public Shipment(string url) {
            this.Url = url;
        }
        
        public SecurityHeader SecurityHeaderValue {
            get {
                return this.SecurityHeaderValueField;
            }
            set {
                this.SecurityHeaderValueField = value;
            }
        }
        
        public event SendCompletedEventHandler SendCompleted;
        
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cesun.edu/Send", RequestNamespace="http://www.cesun.edu", ResponseNamespace="http://www.cesun.edu", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public bool Send(string to, string from) {
            object[] results = this.Invoke("Send", new object[] {
                        to,
                        from});
            return ((bool)(results[0]));
        }
        
        public System.IAsyncResult BeginSend(string to, string from, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Send", new object[] {
                        to,
                        from}, callback, asyncState);
        }
        
        public bool EndSend(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        public void SendAsync(string to, string from) {
            this.SendAsync(to, from, null);
        }
        
        public void SendAsync(string to, string from, object userState) {
            if ((this.SendOperationCompleted == null)) {
                this.SendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCompleted);
            }
            this.InvokeAsync("Send", new object[] {
                        to,
                        from}, this.SendOperationCompleted, userState);
        }
        
        private void OnSendCompleted(object arg) {
            if ((this.SendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCompleted(this, new SendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cesun.edu")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.cesun.edu", IsNullable=true)]
    public partial class SecurityHeader : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Token;
    }
    
    public partial class SendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    public delegate void SendCompletedEventHandler(object sender, SendCompletedEventArgs args);
}
